---
micronaut:
  application:
    name: micronaut-liquibase-rabbit

---
#rabbitmq:
#  uri: amqp://localhost:5672

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''    
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
      cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
---
liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/changelog.xml'
---
rabbitmq:
  enabled: false